# Generated by Django 5.2.11 on 2026-05-28 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset3DModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(help_text='Stable identifier, e.g. "chiller-01-v1". Used by frontend to fetch by key.', max_length=64, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('chiller', 'Chiller'), ('ahu', 'Air Handling Unit'), ('pump', 'Pump'), ('compressor', 'Compressor'), ('overview', 'Overview / Other')], default='chiller', max_length=32)),
                ('file', models.FileField(help_text='GLB file uploaded via admin', upload_to='3d/glb/')),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Asset 3D model',
                'verbose_name_plural': 'Asset 3D models',
                'db_table': 'asset_3d_model',
                'ordering': ['category', 'key'],
            },
        ),
        migrations.CreateModel(
            name='AssetType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_asset_3d', models.ForeignKey(blank=True, help_text='3D model shown for any Asset of this type unless overridden on the Asset itself.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_types', to='assets.asset3dmodel')),
            ],
            options={
                'verbose_name': 'Asset Type',
                'verbose_name_plural': 'Asset Types',
                'db_table': 'asset_type',
            },
        ),
        migrations.CreateModel(
            name='AssetConfigField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Machine name, e.g. "rated_tr".', max_length=100)),
                ('label', models.CharField(help_text='Display name, e.g. "Rated Capacity".', max_length=120)),
                ('section', models.CharField(blank=True, default='General', help_text='Group header this field renders under.', max_length=80)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('data_type', models.CharField(choices=[('number', 'Number'), ('text', 'Text'), ('bool', 'Boolean')], default='number', max_length=10)),
                ('unit', models.CharField(blank=True, default='', max_length=20)),
                ('default_value', models.CharField(blank=True, default='', help_text='Fallback used when an Asset has no AssetConfigValue for this field.', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='config_fields', to='assets.assettype')),
            ],
            options={
                'verbose_name': 'Asset config field',
                'verbose_name_plural': 'Asset config fields',
                'db_table': 'asset_config_field',
                'ordering': ['asset_type', 'display_order', 'key'],
                'unique_together': {('asset_type', 'key')},
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('db_link', models.CharField(default='postgresql://postgres@/lt_panels?host=/run/postgresql', help_text='libpq connection string used to fetch timeseries values.', max_length=255)),
                ('table_name', models.CharField(default='asset_readings', help_text='Timeseries table name in the external DB, e.g. asset_chiller_01.', max_length=100)),
                ('asset_id', models.CharField(blank=True, db_index=True, default='', help_text='Filter value for the asset_id column in the timeseries table.', max_length=100)),
                ('group', models.CharField(blank=True, default='', help_text='Logical grouping this asset rolls up into on fan-out/overview pages (e.g. "HVAC Plant", "Compressed Air"). Static metadata.', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coupler', models.ManyToManyField(blank=True, related_name='+', to='assets.asset')),
                ('incoming', models.ManyToManyField(blank=True, related_name='+', to='assets.asset')),
                ('outgoing', models.ManyToManyField(blank=True, related_name='+', to='assets.asset')),
                ('spare', models.ManyToManyField(blank=True, related_name='+', to='assets.asset')),
                ('asset_3d_override', models.ForeignKey(blank=True, help_text='Per-Asset override; if unset, falls back to asset_type.default_asset_3d.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='override_for_assets', to='assets.asset3dmodel')),
                ('asset_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='assets.assettype')),
            ],
            options={
                'verbose_name': 'Asset',
                'verbose_name_plural': 'Assets',
                'db_table': 'asset',
            },
        ),
        migrations.CreateModel(
            name='AssetConfigValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, default='', help_text='Stored as text; cast per field.data_type on read.', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='config_values', to='assets.asset')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='assets.assetconfigfield')),
            ],
            options={
                'verbose_name': 'Asset config value',
                'verbose_name_plural': 'Asset config values',
                'db_table': 'asset_config_value',
                'unique_together': {('asset', 'field')},
            },
        ),
        migrations.CreateModel(
            name='AssetParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Display name, e.g. "Chilled Water Supply Temp"', max_length=100)),
                ('column_name', models.CharField(db_index=True, help_text='Exact column in the timeseries table, e.g. chw_supply_temp_c', max_length=100)),
                ('kind', models.CharField(choices=[('measured', 'Measured'), ('derived', 'Derived')], default='measured', max_length=10)),
                ('unit', models.CharField(blank=True, default='', max_length=20)),
                ('spec', models.CharField(blank=True, default='', help_text='Spec reference', max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='assets.assettype')),
            ],
            options={
                'verbose_name': 'Asset Parameter',
                'verbose_name_plural': 'Asset Parameters',
                'db_table': 'asset_parameter',
                'unique_together': {('asset_type', 'column_name')},
            },
        ),
    ]
