# Generated by Django 5.2.11 on 2026-05-29 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='group',
            field=models.CharField(blank=True, default='', help_text='Logical grouping this asset rolls up into on fan-out/overview pages (e.g. "Power Backup", "HT Yard"). Static metadata.', max_length=100),
        ),
        migrations.AlterField(
            model_name='asset',
            name='table_name',
            field=models.CharField(default='asset_readings', help_text='Timeseries table name in the external DB, e.g. asset_ups_01.', max_length=100),
        ),
        migrations.AlterField(
            model_name='asset3dmodel',
            name='category',
            field=models.CharField(choices=[('lt_transformer', 'LT Transformer'), ('ht_transformer', 'HT Transformer'), ('dg', 'Diesel Generator'), ('ups', 'UPS'), ('overview', 'Overview / Other')], default='ups', max_length=32),
        ),
        migrations.AlterField(
            model_name='asset3dmodel',
            name='key',
            field=models.SlugField(help_text='Stable identifier, e.g. "ups-01-v1". Used by frontend to fetch by key.', max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='assetconfigfield',
            name='key',
            field=models.CharField(help_text='Machine name, e.g. "rated_kva".', max_length=100),
        ),
        migrations.AlterField(
            model_name='assetparameter',
            name='column_name',
            field=models.CharField(db_index=True, help_text='Exact column in the timeseries table, e.g. battery_soc_pct', max_length=100),
        ),
        migrations.AlterField(
            model_name='assetparameter',
            name='name',
            field=models.CharField(help_text='Display name, e.g. "Battery State of Charge"', max_length=100),
        ),
    ]
