# Generated by Django 5.2.11 on 2026-05-29 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_alter_asset_group_alter_asset_table_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='asset_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text="Filter value for the timeseries table's panel_id column, e.g. 'MFM-UPS-047'.", max_length=100),
        ),
    ]
