"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-2y3&^6)iwxrd_g*8(^!5^9uf(hut-%^*i#ct73nvsh)d_rym-e'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'daphne',  # must be first so its runserver wins over Django's
    'jazzmin',  # must precede django.contrib.admin to override its templates
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'channels',
    'corsheaders',
    'rest_framework',
    'kcauth',
    'lt_panels',
    'assets',
]

# Keycloak JWT auth (ported from LoggerFast). The authentication class is
# active globally so any Bearer/X-Agent-Token is validated and exposed as
# request.auth (claims) + request.user (KeycloakUser). Permissions are left
# open (AllowAny) so existing endpoints keep working — attach
# kcauth.permissions.{SafeOrWrite,RequireLoggerRead,RequireLoggerWrite} per
# view, or flip DEFAULT_PERMISSION_CLASSES below to enforce globally.
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'kcauth.authentication.KeycloakAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
}

ASGI_APPLICATION = 'backend.asgi.application'

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels.layers.InMemoryChannelLayer',
    },
}

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # must precede CommonMiddleware
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'lt_panels.middleware.CacheImmutableMediaMiddleware',
]

# CORS — open for dev / internal Tailscale + LAN access. Tighten in prod.
CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# The DB connection comes from the ONE shared config (pipeline_v48/config/databases.py — the PG_* block / PG_* env).
# Edit the DB there and both ems_backend AND the pipeline follow. (Live logging DB: target_version1 / schema neuract.)
import sys as _sys
_sys.path.insert(0, str(Path(__file__).resolve().parent.parent.parent))   # → pipeline_v48 (so config/ is importable)
from config.databases import django_db   # noqa: E402
DATABASES = {'default': django_db()}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Jazzmin admin theme
# https://django-jazzmin.readthedocs.io/configuration/
JAZZMIN_SETTINGS = {
    'site_title': 'CMD Admin',
    'site_header': 'CMD Admin',
    'site_brand': 'CMD Admin',
    'welcome_sign': 'Welcome to CMD Admin',
    'copyright': 'Neuract',
    'search_model': ['lt_panels.MFM', 'assets.Asset', 'auth.User'],
    'icons': {
        'auth.User': 'fas fa-user',
        'auth.Group': 'fas fa-users',
        'lt_panels.Asset3D': 'fas fa-cube',
        'lt_panels.MFMType': 'fas fa-layer-group',
        'lt_panels.MFM': 'fas fa-gauge-high',
        'lt_panels.Parameter': 'fas fa-sliders',
        'lt_panels.ConfigField': 'fas fa-list-check',
        'lt_panels.ConfigValue': 'fas fa-pen-to-square',
        'assets.Asset3DModel': 'fas fa-cubes',
        'assets.AssetType': 'fas fa-layer-group',
        'assets.Asset': 'fas fa-server',
        'assets.AssetParameter': 'fas fa-sliders',
        'assets.AssetConfigField': 'fas fa-list-check',
        'assets.AssetConfigValue': 'fas fa-pen-to-square',
    },
    'default_icon_parents': 'fas fa-chevron-circle-right',
    'default_icon_children': 'fas fa-circle',
    'show_ui_builder': True,
}

JAZZMIN_UI_TWEAKS = {
    'theme': 'default',
    'navbar': 'navbar-white navbar-light',
    'sidebar': 'sidebar-dark-primary',
}
