#!/usr/bin/env bash
# link-cmd-v2.sh — (re)point the ONE machine-specific CMD_V2 anchor [audit R3].
# Writes BOTH consumers of that fact:
#   · cmd-v2-src symlink        — vite's @cmd-v2 alias fallback (vite.config.ts realpaths it; env CMD_V2_ROOT overrides)
#   · tsconfig.cmdv2.json       — the tsc path mapping. MUST be the real absolute path: mapping through the symlink
#                                 makes tsc resolve CMD_V2's imports against host/web/node_modules (390 type errors).
# Run once per machine / whenever CMD_V2 moves:  CMD_V2_ROOT=/path/to/CMD_V2 bash scripts/link-cmd-v2.sh
set -euo pipefail
cd "$(dirname "$0")/.."
ROOT="${CMD_V2_ROOT:-/home/rohith/CMD_V2}"
[ -d "$ROOT/src" ] || { echo "CMD_V2 src not found at $ROOT/src" >&2; exit 1; }
ln -sfn "$ROOT/src" cmd-v2-src
cat > tsconfig.cmdv2.json <<JSON
{
  "//": "GENERATED by scripts/link-cmd-v2.sh — the one machine-specific fact (CMD_V2 location). Do not hand-edit.",
  "compilerOptions": {
    "paths": { "@cmd-v2/*": ["$ROOT/src/*"] }
  }
}
JSON
echo "cmd-v2-src -> $ROOT/src ; tsconfig.cmdv2.json updated"
