# Generated by Django 5.2.11 on 2026-05-11 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MFMType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'MFM Type',
                'verbose_name_plural': 'MFM Types',
                'db_table': 'lt_mfm_type',
            },
        ),
        migrations.CreateModel(
            name='MFM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('db_link', models.CharField(help_text='DB connection alias or URL used to fetch parameter values', max_length=255)),
                ('table_name', models.CharField(help_text='Timeseries table name, e.g. panel_readings', max_length=100)),
                ('panel_id', models.CharField(blank=True, default='', help_text='Filter value for panel_id column in the timeseries table', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('incoming', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='lt_panels.mfm')),
                ('outgoing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='lt_panels.mfm')),
                ('spare', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='lt_panels.mfm')),
                ('mfm_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mfms', to='lt_panels.mfmtype')),
            ],
            options={
                'verbose_name': 'MFM',
                'verbose_name_plural': 'MFMs',
                'db_table': 'lt_mfm',
            },
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Display name, e.g. "Active Power Total"', max_length=100)),
                ('column_name', models.CharField(help_text='Exact column in the timeseries table, e.g. active_power_total_kw', max_length=100)),
                ('kind', models.CharField(choices=[('measured', 'Measured'), ('derived', 'Derived')], default='measured', max_length=10)),
                ('unit', models.CharField(blank=True, default='', max_length=20)),
                ('spec', models.CharField(blank=True, default='', help_text='Spec reference, e.g. M5, PQ1, 1.1, 8.5', max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mfm_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='lt_panels.mfmtype')),
            ],
            options={
                'verbose_name': 'Parameter',
                'verbose_name_plural': 'Parameters',
                'db_table': 'lt_parameter',
                'unique_together': {('mfm_type', 'column_name')},
            },
        ),
    ]
