# Generated by Django 5.2.11 on 2026-05-11 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lt_panels', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mfm',
            name='incoming',
        ),
        migrations.RemoveField(
            model_name='mfm',
            name='outgoing',
        ),
        migrations.RemoveField(
            model_name='mfm',
            name='spare',
        ),
        migrations.AddField(
            model_name='mfm',
            name='incoming',
            field=models.ManyToManyField(blank=True, related_name='+', to='lt_panels.mfm'),
        ),
        migrations.AddField(
            model_name='mfm',
            name='outgoing',
            field=models.ManyToManyField(blank=True, related_name='+', to='lt_panels.mfm'),
        ),
        migrations.AddField(
            model_name='mfm',
            name='spare',
            field=models.ManyToManyField(blank=True, related_name='+', to='lt_panels.mfm'),
        ),
    ]
