# Generated by Django 5.2.11 on 2026-05-11 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lt_panels', '0002_remove_mfm_incoming_remove_mfm_outgoing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mfm',
            name='db_link',
            field=models.CharField(default='postgresql://postgres@/lt_panels?host=/run/postgresql', help_text='libpq connection string used to fetch parameter values', max_length=255),
        ),
        migrations.AlterField(
            model_name='mfm',
            name='table_name',
            field=models.CharField(default='panel_readings', help_text='Timeseries table name, e.g. panel_readings', max_length=100),
        ),
    ]
