# Generated by Django 5.2.11 on 2026-05-11 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lt_panels', '0003_alter_mfm_db_link_alter_mfm_table_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='mfm',
            name='coupler',
            field=models.ManyToManyField(blank=True, related_name='+', to='lt_panels.mfm'),
        ),
    ]
