# Generated by Django 5.2.11 on 2026-05-12 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lt_panels', '0004_mfm_coupler'),
    ]

    operations = [
        migrations.AddField(
            model_name='mfm',
            name='load_group',
            field=models.CharField(blank=True, default='', help_text='Logical load category this MFM rolls up into on the PCC Panel energy-distribution Sankey (e.g. "UPS backed loads", "Lamination heaters"). Static metadata, not from the timeseries.', max_length=100),
        ),
    ]
