# Generated by Django 5.2.11 on 2026-05-25 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lt_panels', '0005_mfm_load_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mfm',
            name='panel_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Filter value for panel_id column in the timeseries table', max_length=100),
        ),
    ]
