# Generated by Django 5.2.11 on 2026-05-25 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lt_panels', '0006_alter_mfm_panel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameter',
            name='column_name',
            field=models.CharField(db_index=True, help_text='Exact column in the timeseries table, e.g. active_power_total_kw', max_length=100),
        ),
    ]
