# Generated by Django 5.2.11 on 2026-05-26 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lt_panels', '0007_alter_parameter_column_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset3D',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(help_text='Stable identifier, e.g. "pcc1a-v1". Used by frontend to fetch by key.', max_length=64, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('lt_panel', 'LT Panel'), ('ht_panel', 'HT Panel'), ('ups', 'UPS'), ('transformer', 'Transformer'), ('apfc', 'APFC'), ('dg', 'Diesel Generator'), ('overview', 'Overview / Other')], default='lt_panel', max_length=32)),
                ('file', models.FileField(help_text='GLB file uploaded via admin', upload_to='3d/glb/')),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '3D Asset',
                'verbose_name_plural': '3D Assets',
                'db_table': 'lt_asset_3d',
                'ordering': ['category', 'key'],
            },
        ),
        migrations.AddField(
            model_name='mfm',
            name='asset_3d_override',
            field=models.ForeignKey(blank=True, help_text='Per-MFM override; if unset, falls back to mfm_type.default_asset_3d.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='override_for_mfms', to='lt_panels.asset3d'),
        ),
        migrations.AddField(
            model_name='mfmtype',
            name='default_asset_3d',
            field=models.ForeignKey(blank=True, help_text='3D model shown for any MFM of this type unless overridden on the MFM itself.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_types', to='lt_panels.asset3d'),
        ),
    ]
