# Generated by Django 5.2.11 on 2026-05-28 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lt_panels', '0008_asset3d_mfm_asset_3d_override_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Machine name, e.g. "rated_kva", "nominal_voltage_v".', max_length=100)),
                ('label', models.CharField(help_text='Display name, e.g. "Rated Capacity".', max_length=120)),
                ('data_type', models.CharField(choices=[('number', 'Number'), ('text', 'Text'), ('bool', 'Boolean')], default='number', max_length=10)),
                ('unit', models.CharField(blank=True, default='', help_text='e.g. "kVA", "V", "MVAh".', max_length=20)),
                ('default_value', models.CharField(blank=True, default='', help_text='Fallback used when an MFM has no ConfigValue for this field.', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mfm_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='config_fields', to='lt_panels.mfmtype')),
            ],
            options={
                'verbose_name': 'Config field',
                'verbose_name_plural': 'Config fields',
                'db_table': 'lt_config_field',
                'ordering': ['mfm_type', 'key'],
                'unique_together': {('mfm_type', 'key')},
            },
        ),
        migrations.CreateModel(
            name='ConfigValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, default='', help_text='Stored as text; cast per field.data_type on read.', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='lt_panels.configfield')),
                ('mfm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='config_values', to='lt_panels.mfm')),
            ],
            options={
                'verbose_name': 'Config value',
                'verbose_name_plural': 'Config values',
                'db_table': 'lt_config_value',
                'unique_together': {('mfm', 'field')},
            },
        ),
    ]
