# Generated by Django 5.2.11 on 2026-05-28 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lt_panels', '0009_configfield_configvalue'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configfield',
            options={'ordering': ['mfm_type', 'display_order', 'key'], 'verbose_name': 'Config field', 'verbose_name_plural': 'Config fields'},
        ),
        migrations.AddField(
            model_name='configfield',
            name='display_order',
            field=models.PositiveIntegerField(default=0, help_text='Sort order within the section (sections sort by their min order).'),
        ),
        migrations.AddField(
            model_name='configfield',
            name='section',
            field=models.CharField(blank=True, default='General', help_text='Group header this field renders under, e.g. "Rating & Identity".', max_length=80),
        ),
    ]
