# Generated by Django 5.2.11 on 2026-05-29 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lt_panels', '0010_alter_configfield_options_configfield_display_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mfm',
            name='power_quality',
            field=models.ManyToManyField(blank=True, related_name='+', to='lt_panels.mfm'),
        ),
    ]
